action_type: "draw_from_deck"
triggers:
  - condition: "is_player_turn"
    game_state: "player_turn"
    out_of_turn: false

validation:
  - check: "is_player_turn"
    player_id: "{player_id}"

effects:
  - type: "draw_from_deck"
    player_id: "{player_id}"

notifications:
  - type: "broadcast"
    event: "game_state_updated"
    data:
      player_id: "{player_id}"

