action_type: "play_card"
triggers:
  - condition: "is_player_turn"
    game_state: "player_turn"
    out_of_turn: false
  - condition: "same_rank_card"
    game_state: "out_of_turn_play"
    out_of_turn: true

validation:
  - check: "player_has_card"
    card_id: "{card_id}"

effects:
  - type: "play_card"
    player_id: "{player_id}"
    card_id: "{card_id}"

notifications:
  - type: "broadcast"
    event: "card_played"
    data:
      player_id: "{player_id}"
      card: "{card_data}"
      is_out_of_turn: "{out_of_turn}"

  - type: "broadcast"
    event: "check_out_of_turn_play"
    data:
      played_card_rank: "{card_rank}"
      timeout: 5000 