action_type: "start_match"
triggers:
  - condition: "is_room_owner"
    game_state: "waiting_for_players"
    out_of_turn: false

validation:
  - check: "is_room_owner"
    player_id: "{player_id}"
  - check: "game_not_started"
    game_phase: "waiting_for_players"
  - check: "minimum_players"
    min_players: 1  # Allow solo play with bot

effects:
  - type: "add_computer_player_if_needed"
    condition: "less_than_two_players"
    bot_name: "Computer"
  
  - type: "start_game_dealing"
    deal_cards: 4
    cards_per_player: 4
    setup_draw_pile: true
    setup_discard_pile: true
  
  - type: "set_game_phase"
    phase: "dealing_cards"
    then: "player_turn"
  
  - type: "set_first_player"
    selection: "first_human_player"
  
  - type: "record_game_start"
    timestamp: "{current_time}"

notifications:
  - type: "broadcast"
    event: "game_started"
    data:
      game_id: "{game_id}"
      game_state: "{game_state}"
      players: "{players}"
      started_by: "{player_id}"
      timestamp: "{current_time}"

  - type: "broadcast"
    event: "game_phase_changed"
    data:
      game_id: "{game_id}"
      new_phase: "player_turn"
      current_player: "{current_player_id}"
