// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE7txijRmTfhUFic-tRxbGzk5IzAOWGxE',
    appId: '1:851791240618:web:ede6432d0b6b26fc1e9fd3',
    messagingSenderId: '851791240618',
    projectId: 'dutch-mt',
    authDomain: 'dutch-mt.firebaseapp.com',
    storageBucket: 'dutch-mt.firebasestorage.app',
    measurementId: 'G-162F9WTV1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKr6_Xvqcp3QPoufRCjxNjUvkCzr0QPZM',
    appId: '1:851791240618:android:5a93156055ac2e071e9fd3',
    messagingSenderId: '851791240618',
    projectId: 'dutch-mt',
    storageBucket: 'dutch-mt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLsQTaxG9ZL37qk-sC2ATYwkn2zP67XE',
    appId: '1:851791240618:ios:aaba0fb606406b351e9fd3',
    messagingSenderId: '851791240618',
    projectId: 'dutch-mt',
    storageBucket: 'dutch-mt.firebasestorage.app',
    iosBundleId: 'com.reignofplay.dutch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLsQTaxG9ZL37qk-sC2ATYwkn2zP67XE',
    appId: '1:851791240618:ios:aaba0fb606406b351e9fd3',
    messagingSenderId: '851791240618',
    projectId: 'dutch-mt',
    storageBucket: 'dutch-mt.firebasestorage.app',
    iosBundleId: 'com.reignofplay.dutch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE7txijRmTfhUFic-tRxbGzk5IzAOWGxE',
    appId: '1:851791240618:web:2dbfd8d9931959881e9fd3',
    messagingSenderId: '851791240618',
    projectId: 'dutch-mt',
    authDomain: 'dutch-mt.firebaseapp.com',
    storageBucket: 'dutch-mt.firebasestorage.app',
    measurementId: 'G-DZVJHPM6RN',
  );

}