// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Values are injected at build/run time via --dart-define from playbooks/frontend/.env
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Values come from dart-define (sourced from playbooks/frontend/.env by build/launch scripts).
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: ''),
        appId: String.fromEnvironment('FIREBASE_WEB_APP_ID', defaultValue: ''),
        messagingSenderId: String.fromEnvironment('FIREBASE_WEB_MESSAGING_SENDER_ID', defaultValue: ''),
        projectId: String.fromEnvironment('FIREBASE_WEB_PROJECT_ID', defaultValue: ''),
        authDomain: String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN', defaultValue: ''),
        storageBucket: String.fromEnvironment('FIREBASE_WEB_STORAGE_BUCKET', defaultValue: ''),
        measurementId: String.fromEnvironment('FIREBASE_WEB_MEASUREMENT_ID', defaultValue: ''),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: ''),
        appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID', defaultValue: ''),
        messagingSenderId: String.fromEnvironment('FIREBASE_ANDROID_MESSAGING_SENDER_ID', defaultValue: ''),
        projectId: String.fromEnvironment('FIREBASE_ANDROID_PROJECT_ID', defaultValue: ''),
        storageBucket: String.fromEnvironment('FIREBASE_ANDROID_STORAGE_BUCKET', defaultValue: ''),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: ''),
        appId: String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: ''),
        messagingSenderId: String.fromEnvironment('FIREBASE_IOS_MESSAGING_SENDER_ID', defaultValue: ''),
        projectId: String.fromEnvironment('FIREBASE_IOS_PROJECT_ID', defaultValue: ''),
        storageBucket: String.fromEnvironment('FIREBASE_IOS_STORAGE_BUCKET', defaultValue: ''),
        iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: ''),
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: ''),
        appId: String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: ''),
        messagingSenderId: String.fromEnvironment('FIREBASE_IOS_MESSAGING_SENDER_ID', defaultValue: ''),
        projectId: String.fromEnvironment('FIREBASE_IOS_PROJECT_ID', defaultValue: ''),
        storageBucket: String.fromEnvironment('FIREBASE_IOS_STORAGE_BUCKET', defaultValue: ''),
        iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: ''),
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: ''),
        appId: String.fromEnvironment('FIREBASE_WINDOWS_APP_ID', defaultValue: ''),
        messagingSenderId: String.fromEnvironment('FIREBASE_WINDOWS_MESSAGING_SENDER_ID', defaultValue: ''),
        projectId: String.fromEnvironment('FIREBASE_WINDOWS_PROJECT_ID', defaultValue: ''),
        authDomain: String.fromEnvironment('FIREBASE_WINDOWS_AUTH_DOMAIN', defaultValue: ''),
        storageBucket: String.fromEnvironment('FIREBASE_WINDOWS_STORAGE_BUCKET', defaultValue: ''),
        measurementId: String.fromEnvironment('FIREBASE_WINDOWS_MEASUREMENT_ID', defaultValue: ''),
      );
}
