// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Values are injected at build/run time via --dart-define from playbooks/frontend/.env
// String.fromEnvironment must be used in const context, so we define const vars first.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Web
const _webApiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: '');
const _webAppId = String.fromEnvironment('FIREBASE_WEB_APP_ID', defaultValue: '');
const _webMessagingSenderId = String.fromEnvironment('FIREBASE_WEB_MESSAGING_SENDER_ID', defaultValue: '');
const _webProjectId = String.fromEnvironment('FIREBASE_WEB_PROJECT_ID', defaultValue: '');
const _webAuthDomain = String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN', defaultValue: '');
const _webStorageBucket = String.fromEnvironment('FIREBASE_WEB_STORAGE_BUCKET', defaultValue: '');
const _webMeasurementId = String.fromEnvironment('FIREBASE_WEB_MEASUREMENT_ID', defaultValue: '');

// Android
const _androidApiKey = String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: '');
const _androidAppId = String.fromEnvironment('FIREBASE_ANDROID_APP_ID', defaultValue: '');
const _androidMessagingSenderId = String.fromEnvironment('FIREBASE_ANDROID_MESSAGING_SENDER_ID', defaultValue: '');
const _androidProjectId = String.fromEnvironment('FIREBASE_ANDROID_PROJECT_ID', defaultValue: '');
const _androidStorageBucket = String.fromEnvironment('FIREBASE_ANDROID_STORAGE_BUCKET', defaultValue: '');

// iOS / macOS
const _iosApiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: '');
const _iosAppId = String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: '');
const _iosMessagingSenderId = String.fromEnvironment('FIREBASE_IOS_MESSAGING_SENDER_ID', defaultValue: '');
const _iosProjectId = String.fromEnvironment('FIREBASE_IOS_PROJECT_ID', defaultValue: '');
const _iosStorageBucket = String.fromEnvironment('FIREBASE_IOS_STORAGE_BUCKET', defaultValue: '');
const _iosBundleId = String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: '');

// Windows
const _windowsApiKey = String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: '');
const _windowsAppId = String.fromEnvironment('FIREBASE_WINDOWS_APP_ID', defaultValue: '');
const _windowsMessagingSenderId = String.fromEnvironment('FIREBASE_WINDOWS_MESSAGING_SENDER_ID', defaultValue: '');
const _windowsProjectId = String.fromEnvironment('FIREBASE_WINDOWS_PROJECT_ID', defaultValue: '');
const _windowsAuthDomain = String.fromEnvironment('FIREBASE_WINDOWS_AUTH_DOMAIN', defaultValue: '');
const _windowsStorageBucket = String.fromEnvironment('FIREBASE_WINDOWS_STORAGE_BUCKET', defaultValue: '');
const _windowsMeasurementId = String.fromEnvironment('FIREBASE_WINDOWS_MEASUREMENT_ID', defaultValue: '');

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Values come from dart-define (sourced from playbooks/frontend/.env by build/launch scripts).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: _webAppId,
    messagingSenderId: _webMessagingSenderId,
    projectId: _webProjectId,
    authDomain: _webAuthDomain,
    storageBucket: _webStorageBucket,
    measurementId: _webMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: _androidAppId,
    messagingSenderId: _androidMessagingSenderId,
    projectId: _androidProjectId,
    storageBucket: _androidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: _iosAppId,
    messagingSenderId: _iosMessagingSenderId,
    projectId: _iosProjectId,
    storageBucket: _iosStorageBucket,
    iosBundleId: _iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: _iosAppId,
    messagingSenderId: _iosMessagingSenderId,
    projectId: _iosProjectId,
    storageBucket: _iosStorageBucket,
    iosBundleId: _iosBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _windowsApiKey,
    appId: _windowsAppId,
    messagingSenderId: _windowsMessagingSenderId,
    projectId: _windowsProjectId,
    authDomain: _windowsAuthDomain,
    storageBucket: _windowsStorageBucket,
    measurementId: _windowsMeasurementId,
  );
}
