action_type: "call_recall"
triggers:
  - condition: "is_player_turn"
    game_state: "player_turn"
  - condition: "recall_opportunity"
    game_state: "player_turn"

validation:
  - check: "is_player_turn"
    player_id: "{player_id}"
  - check: "has_not_called_recall"
    player_id: "{player_id}"

effects:
  - type: "call_recall"
    player_id: "{player_id}"
  
  - type: "change_game_phase"
    new_phase: "recall_called"
  
  - type: "start_final_round"
    final_round: true

notifications:
  - type: "broadcast"
    event: "recall_called"
    data:
      player_id: "{player_id}"
      phase: "recall_called"
      final_round: true

  - type: "broadcast"
    event: "game_ending"
    data:
      reason: "recall_called"
      called_by: "{player_id}" 