action_type: "place_drawn_card_play"
triggers:
  - condition: "is_player_turn"
    game_state: "player_turn"
    out_of_turn: false

validation:
  - check: "is_player_turn"
    player_id: "{player_id}"
  - check: "has_pending_draw"
    player_id: "{player_id}"

effects:
  - type: "place_drawn_card_play"
    player_id: "{player_id}"

notifications:
  - type: "broadcast"
    event: "card_played"
    data:
      player_id: "{player_id}"

