name: Prepare SDK

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  prepare:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run SDK preparation script
      run: |
        .\scripts\prepare_sdk.ps1

    - name: Upload Flutter SDK
      uses: actions/upload-artifact@v4
      with:
        name: flutter-sdk
        path: flutter-sdk.zip 